services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: festival_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  seeder:
    image: therealbatou/festival-api:1.0.0
    depends_on:
      - db
    command: npm run seed
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: festival_database

  app:
    image: therealbatou/festival-api:1.0.0
    depends_on:
      - db
      - seeder
    ports:
      - "3000:3000"
    environment:
      BASE_URL: http://localhost
      BASE_PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: festival_database

volumes:
  pgdata:
